global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: postgres_exporter
    static_configs:
      - targets: ["localhost:9187"]

  - job_name: kafka_exporter
    static_configs:
      - targets: ["localhost:9308"]

  - job_name: ms-order
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["localhost:8091"]

  - job_name: ms-invoice
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["localhost:8092"]

  - job_name: ms-notification
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["localhost:8093"]

  - job_name: ms-payment
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["localhost:8094"]

  - job_name: ms-shipping
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["localhost:8095"]

  - job_name: ms-customer
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["localhost:8096"]

  - job_name: ms-checkout-orchestrator
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["localhost:8097"]

  - job_name: ms-inventory
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["localhost:8098"]
